# This is a basic workflow to help you get started with Actions
name: CI
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# name: Python Package

# on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]
        python-version:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "pypy-3.7"
          - "pypy-3.8"
        architecture: ["x86", "x64"]
        exclude:
          - os: macos-10.15 # Can't compile Numpy for this implementation.
            python-version: "pypy-3.7"
          - os: macos-10.15
            architecture: "x86"
          - os: ubuntu-20.04
            architecture: "x86"

    steps:
      - name: Install APT dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get install libsndfile1 libsndfile1-dev
#       - name: Install choco for Windows
      - name: Build on Windows
        if: runner.os == 'Windows'
        run: |
          choco install libsndfile
          New-Item -ItemType Junction -Path "C:\libsndfile" -Target "C:\Program Files\libsndfile"
          $Env:windir
          $Env:INCLUDE
          $Env:LIB
          $Env:PATH
          $Env:PATH += ';C:\libsnfile\bin'
          $Env:INCLUDE += ';C:\libsnfile\include'
#Set-Item -Path Env:CGO_LDFLAGS -Value "-LC:\libsndfile\bin"
        
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      - name: Install requirements
        run: pip install numpy pytest cffi
      - name: Install editable package
        run: pip install --editable . --verbose
      - name: Run tests
        run: python -m pytest

